<?php

/**
 * @file
 * Contains google_appliance.page.inc.
 */

/**
 * Prepares variables for google_appliance_search_results templates.
 *
 * Default template: google-appliance-search-results.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - response: A \Drupal\google_appliance\SearchResults\ResultSet object
 *   - form: Search form array.
 */
function template_preprocess_google_appliance_search_results(array &$variables) {

}
